### ISSUE TITLE
Fable.MochaPuppeteerRunner - Missing method LaunchAsync with Puppeteer 2.0.4

### ISSUE THREAD

**Issue by theimowski** [Zaid-Ajaj/Fable.Mocha#25]
Tried to add the library to SAFE template, but when run I got following exception:

```
Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<PuppeteerSharp.Browser> PuppeteerSharp.Puppeteer.LaunchAsync(PuppeteerSharp.LaunchOptions, Microsoft.Extensions.Logging.ILoggerFactory)'.
   at Puppeteer.runTests@71-4.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 386
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
```

resolved versions:
Fable.MochaPuppeteerRunner (1.2)
PuppeteerSharp (2.0.4)

EDIT: works fine if I pin PuppeteerSharp to 1.17.1

**Comment by Zaid-Ajaj** [comment]
Hi there @theimowski the package probably only works with `PuppeteerSharp > 1.17 && < 2.0.0`  I will update and publish a new version soon that uses latest 😄

**Comment by Zaid-Ajaj** [comment]
Published version v1.3 of the runner and it should work ootb with latest puppeteersharp

**Comment by theimowski** [comment]
yup works fine - thanks!

**Comment by theimowski** [comment]
PuppeteerSharp 3.0 has been released [2 days ago](https://www.nuget.org/packages/PuppeteerSharp/), and now there's a similar issue:

```
  Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<PuppeteerSharp.Browser> PuppeteerSharp.Puppeteer.LaunchAsync(PuppeteerSharp.LaunchOptions, Microsoft.Extensions.Logging.ILoggerFactory, PuppeteerSharp.Product)'.
     at Puppeteer.runTests@71-4.Invoke(Unit unitVar)
```

**Comment by Zaid-Ajaj** [comment]
Here we go again :/ please pin puppeteersharp for now, I'll update it sometime soon
